buildd:
	g++ zhaba.cpp --std=c++20 -o zhaba
	./zhaba test.zh

build_fast:
	g++ zhaba.cpp --std=c++20 -o zhaba -O3

test:
	.\zhaba test.zh

build_test:
	g++ zhaba.cpp --std=c++20 -o zhaba
	.\zhaba test.zh
	