#pragma once
#include "Lexer.hpp"
#include "ast_parser.hpp"
#include "definitions_parser.hpp"
#include "expression_parser.hpp"
#include "parser_error.hpp"
#include "syntax_tree_parser.hpp"
#include "type_parser.hpp"
#include "Preproces.hpp"